Jenkinsfile
README.md
api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Startup.cs
api/KS.FiksProtokollValidator.WebAPI/appsettings.DockerCompose.json
docker-compose.yml
fiks-protokoll-validator-api/.helmignore
fiks-protokoll-validator-api/Chart.yaml
fiks-protokoll-validator-api/templates/fiks-protokoll-validator-api.yaml
fiks-protokoll-validator-api/values.yaml
fiks-protokoll-validator-web/.helmignore
fiks-protokoll-validator-web/Chart.yaml
fiks-protokoll-validator-web/templates/fiks-protokoll-validator-web.yaml
fiks-protokoll-validator-web/values.yaml
web-ui/.env
web-ui/.env.production
web-ui/Dockerfile
web-ui/package.json
web-ui/src/components/NewTestSession.vue
web-ui/src/components/StartPage.vue
web-ui/src/components/TestCasePayloadFile.vue
web-ui/src/components/TestSession.vue

**Web-ui bygger til docker og kjører i docker-compose**
Oppsummering av hva som er gjort:
- Dockerfile for web-ui
- Jenkins bygger og publisher docker for web-ui
- Cors enabled for development og docker-compose
- dotenv npm pakken lagt til for å kunne bruke mode
- Henter base-url fra .env filer
- Base-url brukes for å bygge api-url (hvis man kjører rett på utv maskin blir rewrites i devServer proxy brukt)
- Helm-charts og kubernetes ressurser

web-ui som docker app

---

api/KS.FiksProtokollValidator.WebAPI/Controllers/TestSessionsController.cs
api/KS.FiksProtokollValidator.WebAPI/Models/TestRequest.cs
web-ui/src/components/NewTestSession.vue
web-ui/src/components/PayloadFile.vue
web-ui/src/components/TestCase.vue
web-ui/src/components/TestCasePayloadFile.vue

- "Run tests"-button is now disabled if Fiks-konto is not selected
- "Run tests"-button is now disabled if tests are not selected
- Handle send errors in frontend by displaying a message and status code

UX improvements

---

api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.gi.arkivintegrasjon.oppdatering.basis.arkivmelding.v1/NyJournalpostN6/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.politisk.behandling.klient.v1/SendOrienteringssakN1/sampleSendOrienteringssak.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.politisk.behandling.klient.v1/SendUtvalgsakN1/sampleSendUtvalgsak.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.politisk.behandling.tjener.v1/SendVedtakFraUtvalgN1/sampleSendVedtakFraUtvalg.json

Changes to Politisk Behandling model. 
- Updated tests
- Changed encoding on one test not beeing utf-8

Changes to model - updated tests

---

api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksResponseMessageService.cs

Det kom ikke med Id'er i loggingen.

Lagt til mer info i logging

---

web-ui/src/components/TestSession.vue

Lagt til feilmelding ved testsession som ikke finnes i brukergrensesnittet

404 på testsession

---

api/KS.FiksProtokollValidator.WebAPI/Data/TestSeeder.cs

Når man slettet mappen Attachments ble det glemt å slette innholdet i tabell 🤦

Sletter eksisterende vedlegg hvis det trengs

---

api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.gi.plan.klient/RegistrerDispensasjonFraPlanN1/sampleRegistrerDispensasjonFraPlan.json

* changed values inside test file

Small change on test-file

---

api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Validation/FiksResponseValidator.cs
web-ui/package-lock.json
web-ui/package.json
web-ui/src/components/PayloadFileUpload.vue
web-ui/src/main.js

La til font-awesome og viser et checkmark ikon fra det biblioteket hvis man har vellykket lastet opp en fil.

Viser checkmark etter lastet opp egendefinert fil

---

api/KS.FiksProtokollValidator.WebAPI/Logging/CustomLogstashJsonFormatter.cs
api/KS.FiksProtokollValidator.WebAPI/Program.cs

Kopiert fra og gjort på samme måte som for digiorden.

Egen formatter for logstash

---

api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksRequestMessageService.cs
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/HentJournalpostN1/arkivmelding.xml
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/HentJournalpostN1/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/HentJournalpostN2/arkivmelding.xml
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/HentJournalpostN2/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NySaksmappeFX/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/OppdaterMappeSaksansvarligN1/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/Validation/PayloadChecksHelper.cs
api/KS.FiksProtokollValidator.WebAPI/Validation/Resources/ValidationErrorMessages.resx
api/KS.FiksProtokollValidator.WebAPI/Validation/XsdValidator.cs

Ny header for at simulator skal vite hvilke filer den skal hente

Nye testcases og ny header

---

api/KS.FiksProtokollValidator.TestSessionCleanUp/KS.FiksProtokollValidator.TestSessionCleanUp.csproj
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksIOClientConsumerService.cs
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksResponseMessageService.cs
api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Program.cs
api/KS.FiksProtokollValidator.WebAPI/Startup.cs
api/KS.FiksProtokollValidator.WebAPI/Validation/FiksResponseValidator.cs
api/KS.FiksProtokollValidator.WebAPI/Validation/XsdValidator.cs
docker-compose.yml

Fikset problem med migrering validering som trynte pga json i fil som hadde .xml som filtype.

Fikset problem med migrering og validering 

---

fiks-protokoll-validator/templates/fiks-protokoll-validator.yaml

Resten av oppsett gjøres som del av deployment

Oppdatert med to nye secrets som er public og private keys for signering

---

api/KS.FiksProtokollValidator.WebAPI/Data/FiksIOMessageDBContext.cs
api/KS.FiksProtokollValidator.WebAPI/Data/Migrations/20230117131034_AddIsAsiceVerifiedAndPayloadMessagesToFiksResponse.Designer.cs
api/KS.FiksProtokollValidator.WebAPI/Data/Migrations/20230117131034_AddIsAsiceVerifiedAndPayloadMessagesToFiksResponse.cs

Fikset feil i migration og lagt til igjen IDesignTimeDbContextFactory for at EF skal funke
Det var en migration feil pga jeg hadde slettet en migration men glemt å rydde i DB

Fikset feil i migration og lagt til igjen IDesignTimeDbContextFactory

---

api/KS.FiksProtokollValidator.WebAPI/AppSettings.cs
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksProtokollConnectionManager.cs
api/KS.FiksProtokollValidator.WebAPI/appsettings.json

Dette ble et problem pga configmap og env variables. Det ble til en string og ikke en array med ferdig objekter.

Måtte ha json i json pga dette skal være en env varible hentet fra configmap

---

api/KS.FiksProtokollValidator.WebAPI/Validation/FiksResponseValidator.cs
api/KS.FiksProtokollValidator.WebAPI/Validation/Resources/ValidationErrorMessages.resx

Vise eventuelt bedre feilmelding i validatoren når det er en ASiC feil
Ref jira [FO-97](https://ksfiks.atlassian.net/browse/FO-97)
[FO-97]: https://ksfiks.atlassian.net/browse/FO-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lagt til asice feilmelding ut til rapporten som vises i validator

---

api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Validation/PayloadChecksHelper.cs

Oppdateringer av nuget-pakker og rydding.
KS.Fiks.Protokoller.V1 er deprecated og ble tatt bort. Da måtte det ryddes litt i koden også.

Oppgradering av nuget pakker og tatt bort pakke som er deprecated

---

api/KS.FiksProtokollValidator.Tests/KS.FiksProtokollValidator.Tests.csproj
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksProtokollConnectionManager.cs
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksProtokollConnectionService.cs
api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksResponseMessageService.cs
api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Program.cs
api/KS.FiksProtokollValidator.WebAPI/Startup.cs

Har ikke behov lenger for funksjonaliteten som sørger for å reconnecte

Oppdatert til ny Fiks IO klient og endringer i henhold til det

---

Jenkinsfile
api/KS.FiksProtokollValidator.WebAPI/FiksIO/TjenerMessagesSubscriber.cs
web-ui/Dockerfile

Lagt til meldingsid i logging når den ikke klarer å matche melding inn med melding ut

Manglet informasjon om meldingsid i loggmelding

---

docker-compose.yml

Ref jira sak https://ksfiks.atlassian.net/browse/FO-168

Endret til ny docker image for sqlexpress

---

api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NyJournalpostN1/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NyJournalpostN6/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NyJournalpostN8/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NyMappeMedJournalpostN1/testInformation.json
api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.arkiv.v1/NySaksmappeN1/testInformation.json

Oppdatert testinformasjonsfiler. Endret saksaar og journalaar fra 2024 -> 2025.

Oppdatert testinformation journalaar og saksaar fra 2024 -> 2025

---

api/KS.FiksProtokollValidator.WebAPI/KS.FiksProtokollValidator.WebAPI.csproj
api/KS.FiksProtokollValidator.WebAPI/Schemas/README.md

En midlertidig fiks. Bør se på muligheten for å lage mappen med alle json schemas ved bygging av Docker image

Laget en Schemas mappe som skal være opprettet
